import Head from 'next/head'
import Image from 'next/image'
import { ConnectButton } from '@rainbow-me/rainbowkit';
import Header from '../components/Header';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="text-white bg-black m-2 h-auto h-min-screen">
        <div className="p-10 flex flex-row flex-wrap justify-center">
          
          <div className="mt-4 text-center h-6/12 flex flex-row flex-wrap justify-center">
            <div className=" w-full h-fit">
              BOEDO
            </div>
            <div className=" w-full h-fit">
              MARKETPLACE
            </div>     
            <div className='flex flex-row flex-wrap justify-center w-full'>
              BUILT BY AMIGOS
            </div>
            <Link href="/mint">
              <a style={{ textDecoration: "underline"}} >
                GO TO MINT PAGE
              </a>  
            </Link>             
          </div>
        </div>

      </main>

    </div>
  )
}
